### ISSUE TITLE
One does not simply change js class name

### ISSUE THREAD

**Issue by aodavit-d** [areviksol/aobyte-intership-arevik-mkrtchyan#2]
`TagElement.name = className` will not change class name in javascript 

https://github.com/areviksol/aobyte-intership-arevik-mkrtchyan/blob/a668dfac97b339a75cce86572731be637df245e6/Homework_dom/script.js#L53

**Comment by areviksol** [comment]
Can I use Object.defineProperty() function?

**Comment by aodavit-d** [comment]
You can try and then debug to see if the class takes that name

But if you don't find any way to create generic class in JS, feel free to write duplicate code, as I understand for this task it's not necessary to write DRY code

**Comment by areviksol** [comment]
Thank you for your suggestion. I implemented your advice and successfully fixed the issue by using Object.defineProperty() in JavaScript.
